package org.dentalsoft.cabinetdentalsoft.enums;

public enum CategorieActe {
    PREVENTION,CHIRURGIE,ORTHODONTIE,IMPLANTOLOGIE, SOINS_DES_CARIES,PROTHESES_DENTAIRES,DIAGNOSTIC,SOINS_DES_TISSUS_MOUS
}
